
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Libuscador.Models
{

using System;
    using System.Collections.Generic;
    
public partial class AUTORES
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AUTORES()
    {

        this.LibrosxAutor = new HashSet<LibrosxAutor>();

    }


    public int Aut_Id { get; set; }

    public string Aut_Nombre { get; set; }

    public string Pais { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LibrosxAutor> LibrosxAutor { get; set; }

}

}
