
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Libuscador.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EDITORIALES
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EDITORIALES()
    {

        this.LibrosxEditorial = new HashSet<LibrosxEditorial>();

    }


    public int Ed_Id { get; set; }

    public string Nombre_editorial { get; set; }

    public string Pagina_web { get; set; }

    public string Pais { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LibrosxEditorial> LibrosxEditorial { get; set; }

}

}
